// import React from "react";

// import { useState } from "react";

// function faqsthree() {
//     const [activeIndex, setActiveIndex] = useState(null);

//   const toggleAnswer = (index) => {
//     setActiveIndex(activeIndex === index ? null : index);
//   };
    
//   return (
//     <>
//            <div className="containery">
//         <div className={`accordionf ${activeIndex === 0 ? "border" : ""}`}>
//           <div className="questiona" onClick={() => toggleAnswer(0)}>
//             <h5> What types of data points can I access with Jungle Scout’s Competitive Intelligence tool?</h5>
//             <div
//               className={`circle-plus ${
//                 activeIndex === 0 ? "opened" : "closed"
//               }`}
//             >
//               <div className="circle">
//                 <div className="horizontal"></div>
//                 <div className="vertical"></div>
//               </div>
//             </div>
//           </div>
//           <div
//             className={`answer ${activeIndex === 0 ? "active" : ""}`}
//             style={{ maxHeight: activeIndex === 0 ? "1000px" : "0" }}
//           >
//             <p>
//             With Jungle Scout’s Competitive Intelligence tool, you can access a variety of data points that provide insights both at the market level and at the individual ASIN level:
//               <p>Market Level Data:</p>
//               <ul>
//                 <li>Market Share: Understand the distribution of market share among different competitors in your category.</li>
//                 <li>Market Revenue: Gain insights into the total revenue generated within your market.</li>
//                 <li>Market Unit Sales: Track the total number of units sold across the market.</li>
//               </ul>
//               <p>Individual ASIN Level Data:</p>
//               <ul>
//                 <li>Revenue (Last 12 Months): See the total revenue generated by a specific ASIN over the past year.</li>
//                 <li>Unit Sales (Last 12 Months): Monitor the total number of units sold for a specific ASIN in the last 12 months.</li>
//                 <li>Average Price (Last 12 Months): Review the average selling price of an ASIN over the past year.</li>
//                 <li>Rating (Total): Check the overall rating of a specific product based on customer reviews.</li>
//                 <li>Reviews (Total): Access the total number of reviews a product has received.</li>
//               </ul>
//               <p>By leveraging these data points, you can make informed decisions to enhance your product listings, optimize pricing strategies, and more to gain a competitive edge in the Amazon marketplace.</p>
//             </p>
//           </div>
//         </div>
//       </div>
//     </>
//   )
// }

// export default faqsthree


import React, { useState } from "react";

function FaqsThree() {
  const [activeIndex, setActiveIndex] = useState(null);

  const toggleAnswer = (index) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  return (
    <>
      <div className="containery">
        <div className={`accordionf ${activeIndex === 0 ? "border" : ""}`}>
          <div className="questiona" onClick={() => toggleAnswer(0)}>
            <h6 className="fw-bolder">
              What types of data points can I access with Jungle Scout’s Competitive Intelligence tool?
            </h6>
            <div
              className={`circle-plus ${
                activeIndex === 0 ? "opened" : "closed"
              }`}
            >
              <div className="circle">
                <div className="horizontal"></div>
                <div className="vertical"></div>
              </div>
            </div>
          </div>
          <div
            className={`answer ${activeIndex === 0 ? "active" : ""}`}
            style={{ maxHeight: activeIndex === 0 ? "1000px" : "0" }}
          >
            <p>
              With Jungle Scout’s Competitive Intelligence tool, you can access a variety of data points that provide insights both at the market level and at the individual ASIN level:
            </p>
            <p><strong>Market Level Data:</strong></p>
            <ul>
              <li>Market Share: Understand the distribution of market share among different competitors in your category.</li>
              <li>Market Revenue: Gain insights into the total revenue generated within your market.</li>
              <li>Market Unit Sales: Track the total number of units sold across the market.</li>
            </ul>
            <p><strong>Individual ASIN Level Data:</strong></p>
            <ul>
              <li>Revenue (Last 12 Months): See the total revenue generated by a specific ASIN over the past year.</li>
              <li>Unit Sales (Last 12 Months): Monitor the total number of units sold for a specific ASIN in the last 12 months.</li>
              <li>Average Price (Last 12 Months): Review the average selling price of an ASIN over the past year.</li>
              <li>Rating (Total): Check the overall rating of a specific product based on customer reviews.</li>
              <li>Reviews (Total): Access the total number of reviews a product has received.</li>
            </ul>
            <p>
              By leveraging these data points, you can make informed decisions to enhance your product listings, optimize pricing strategies, and more to gain a competitive edge in the Amazon marketplace.
            </p>
          </div>
        </div>
      </div>
    </>
  );
}

export default FaqsThree;
